# Generated by Django 5.2.13 on 2026-05-29 11:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الكعكة')),
                ('flavor', models.CharField(choices=[('chocolate', 'شوكولاتة'), ('vanilla', 'فانيليا'), ('strawberry', 'فراولة'), ('red_velvet', 'ريد فلفت'), ('lemon', 'ليمون'), ('caramel', 'كراميل')], max_length=50, verbose_name='النكهة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('image', models.ImageField(blank=True, upload_to='cakes/', verbose_name='الصورة')),
                ('is_available', models.BooleanField(default=True, verbose_name='متاحة')),
            ],
            options={
                'verbose_name': 'كعكة',
                'verbose_name_plural': 'الكعكات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='الوزن بالكيلو')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='الكمية')),
                ('total_price', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='المبلغ الإجمالي')),
                ('delivery_date', models.DateField(verbose_name='تاريخ الاستلام أو التوصيل')),
                ('delivery_address', models.TextField(verbose_name='العنوان')),
                ('special_requests', models.TextField(blank=True, verbose_name='طلبات خاصة')),
                ('status', models.CharField(choices=[('pending', 'بانتظار الدفع'), ('confirmed', 'مؤكد'), ('cancelled', 'ملغي'), ('completed', 'مكتمل')], default='pending', max_length=20, verbose_name='حالة الحجز')),
                ('payment_status', models.CharField(choices=[('unpaid', 'غير مدفوع'), ('paid', 'مدفوع'), ('refunded', 'مسترجع')], default='unpaid', max_length=20, verbose_name='حالة الدفع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cake_bookings', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='bookings.cake', verbose_name='الكعكة')),
            ],
            options={
                'verbose_name': 'حجز',
                'verbose_name_plural': 'الحجوزات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ')),
                ('payment_method', models.CharField(choices=[('credit_card', 'بطاقة ائتمان'), ('paypal', 'باي بال'), ('bank_transfer', 'تحويل بنكي')], max_length=50, verbose_name='طريقة الدفع')),
                ('transaction_id', models.CharField(blank=True, max_length=100, verbose_name='رقم العملية')),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='وقت الدفع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='bookings.booking', verbose_name='الحجز')),
            ],
            options={
                'verbose_name': 'دفعة',
                'verbose_name_plural': 'المدفوعات',
                'ordering': ['-created_at'],
            },
        ),
    ]
