# Generated by Django 5.2.13 on 2026-05-29 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('thawani_omannet', 'ثواني - بطاقات عمان نت والبطاقات البنكية'), ('bank_muscat_gateway', 'بوابة بنك مسقط للدفع الإلكتروني'), ('oman_bank_transfer', 'تحويل بنكي داخل سلطنة عمان')], max_length=50, verbose_name='طريقة الدفع'),
        ),
    ]
